<?php
namespace app\erp\controller\template_message;
use app\base\controller\WxApi;
use app\base\model\PersonnelRoleNodeAccess;
use app\worker\controller\WechatMessage;
use mikkle\tp_wechat\Wechat;
use think\Db;
use think\Log;
use think\Url;

/**
 * Created by PhpStorm.
 * Power By Mikkle
 * Email：776329498@qq.com
 * Date: 2017/8/31
 * Time: 14:21
 */
class YzfErp extends TemplateBase
{

    protected $options;
    protected $mission;
    protected $template;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->options = YzfErpOptions::$options;
        $this->mission = YzfErpOptions::$mission;

    }


    /**
     * Power: Mikkle
     * Email：776329498@qq.com
     * @param $type 公告类型(1 公司 2 部门)
     * @param $guid 公告Id
     */
    public function superNotice($type,$guid){




    }


    public function superReview($type,$guid=""){
        if(!$this->checkOptions($type)){
            Log::error("{$type}的配置参数不存在或不全!");
            return false;
        }
        $type = $this->options[$type];
        if (!$this->uuid){
            Log::error("用户未登录");
            return false;
        }
        $company_id = $this->member_info["company_id"];
        $uuid_name = $this->member_info["name"];
        $touser_list=$this->getReviewUuidByNode($type["node"],["company_id"=>$company_id,"status"=>1]);
        $assign_data=[];
        switch(true){
            case (!empty($touser_list)):   //简单模式
                foreach($touser_list as $value){
                    if (empty($value)) {
                        continue;
                    }
                    $assign_data= [
                        "ToUserName"=>$value,
                        "url"=> Url::build($type["url"],[],"",true),
                        "first"=> "云紫峰ERP温馨提示,你有一个[{$type["title"]}]需要审核". (empty($uuid_name)?"":",提交人:$uuid_name"),
                        "keyword1"=>"{$type["title"]}审核",
                        "keyword2"=>date("Y-m-d H:i:s",time()),
                        "remark"=>"点击查看具体内容"
                    ];
                    $template = $this->assignTemplate("mission",$assign_data);
                    //添加异步命令行发送模版消息
                    $re = WechatMessage::add($template,"erp_options");
                  //  $re=WxApi::instance("erp_options")->sendTemplateMessage($template);
                    //dump($re);
                    Log::notice("发送{$uuid_name}提交的{$type["title"]}审核模版消息成功!$re");
                }

                break;
            default:
        }
    }

    protected function getReviewUuidByNode($node,$map=[]){
        $role_list_from_node = Db::table("mk_personnel_role_node_access")->where(["node_id"=>["in",$node]])->column("role_id");
        $uuid_list_from_node = Db::table("mk_personnel_user")->where(["role_id"=>["in",$role_list_from_node]])->where($map)->column("we_openid");
        return array_unique($uuid_list_from_node);
    }

    protected function checkOptions($type){
        if(isset($this->options[$type])){

            return true;
        }else{
            return false;
        }

    }






}