<?php return array (
    //市场部
    'market'=>array(
        'title'=>'装企ERP部门数据配置',
        'content'=>'是否创建该部门：市场部',
        'desc'=>'说明：此操作将会帮你创建一个市场部部门，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createDepartmentMarket'),
        'next'=>url('install/createJobsMarket'),
        'skip'=>url("install/createDepartmentService"),
    ),
    //客服部
    'service'=>array(
        'title'=>'装企ERP部门数据配置',
        'content'=>'是否创建该部门：客服部',
        'desc'=>'说明：此操作将会帮你创建一个客服部部门，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createDepartmentService'),
        'skip'=>url("install/createDepartmentMatters"),
    ),
    //人事部
    'matters'=>array(
        'title'=>'装企ERP部门数据配置',
        'content'=>'是否创建该部门：人事部',
        'desc'=>'说明：此操作将会帮你创建一个人事部部门，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createDepartmentMatters'),
        'skip'=>url("install/createDepartmentFinance"),
    ),
    //财务部
    'finance'=>array(
        'title'=>'装企ERP部门数据配置',
        'content'=>'是否创建该部门：财务部',
        'desc'=>'说明：此操作将会帮你创建一个财务部部门，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createDepartmentFinance'),
        'skip'=>url("install/createDepartmentDesign"),
    ),
    //设计部
    'design'=>array(
        'title'=>'装企ERP部门数据配置',
        'content'=>'是否创建该部门：设计部',
        'desc'=>'说明：此操作将会帮你创建一个设计部部门，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createDepartmentDesign'),
        'skip'=>url("install/createDepartmentEngineering"),
    ),
    //工程部
    'engineering'=>array(
        'title'=>'装企ERP部门数据配置',
        'content'=>'是否创建该部门：工程部',
        'desc'=>'说明：此操作将会帮你创建一个工程部部门，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createDepartmentEngineering'),
        'skip'=>url("install/createDepartmentMaterial"),
    ),
    //材料部
    'material '=>array(
        'title'=>'装企ERP部门数据配置',
        'content'=>'是否创建该部门：材料部',
        'desc'=>'说明：此操作将会帮你创建一个材料部部门，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createDepartmentMaterial'),
        'skip'=>url("install/createDepartmentC"),
    )

);