<?php return array (
    //市场部
    'market'=>array(
        'title'=>'装企ERP职位数据配置',
        'content'=>'是否创建以下职位：',
        'desc'=>'说明：此操作将会帮你创建职位，如需要，请点击下一步，否则点击跳过。',
        'jobs_json'=>[
            '0'=>['jobs_name'=>'业务员'],
            '1'=>['jobs_name'=>'市场经理']
        ],
        'apply'=>url('install/createJobsMarket'),
        'next'=>url('install/createRoleService'),
        'skip'=>url("install/createJobsService"),
    ),
    //客服部
    'service'=>array(
        'title'=>'装企ERP职位数据配置',
        'content'=>'是否创建该部门：客服部',
        'desc'=>'说明：此操作将会帮你创建职位，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createJobsService'),
        'skip'=>url("install/createJobsMatters"),
    ),
    //人事部
    'matters'=>array(
        'title'=>'装企ERP职位数据配置',
        'content'=>'是否创建以下职位：',
        'desc'=>'说明：此操作将会帮你创建职位，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createJobsMatters'),
        'skip'=>url("install/createJobsFinance"),
    ),
    //财务部
    'finance'=>array(
        'title'=>'装企ERP职位数据配置',
        'content'=>'是否创建以下职位：',
        'desc'=>'说明：此操作将会帮你创建职位，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createJobsFinance'),
        'skip'=>url("install/createJobsDesign"),
    ),
    //设计部
    'design'=>array(
        'title'=>'装企ERP职位数据配置',
        'content'=>'是否创建以下职位：',
        'desc'=>'说明：此操作将会帮你创建职位，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createJobsDesign'),
        'skip'=>url("install/createJobsEngineering"),
    ),
    //工程部
    'engineering'=>array(
        'title'=>'装企ERP职位数据配置',
        'content'=>'是否创建以下职位：',
        'desc'=>'说明：此操作将会帮你创建职位，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createJobsEngineering'),
        'skip'=>url("install/createJobsMaterial"),
    ),
    //材料部
    'material '=>array(
        'title'=>'装企ERP职位数据配置',
        'content'=>'是否创建以下职位：',
        'desc'=>'说明：此操作将会帮你创建职位，如需要，请点击下一步，否则点击跳过。',
        'apply'=>url('install/createJobsMaterial'),
        'skip'=>url("install/createDepartmentC"),
    )

);