<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/23
 * Time: 13:02
 */

namespace app\erp\controller;

use app\base\controller\PDF;
use app\base\controller\RedisHash;
use app\base\controller\Word;
use app\base\model\Base;
use app\base\model\budget\BudgetBookNumber;
use app\base\model\budget\DefaultProjectCopy;
use app\base\model\budget\DefaultRateCopy;
use app\base\model\budget\PrintRequest;
use app\base\model\BudgetDefaultBook;
use app\base\model\BudgetDefaultRate;
use app\base\model\BudgetDefaultProject;
use app\base\model\build\BuildContractRint;
use app\base\model\build\BuildProjectCategoryPhoto;
use app\base\model\build\BuildProjectCategoryTime;
use app\base\model\build\BuildProjectPercentage;
use app\base\model\build\BuildProjectTime;
use app\base\model\build\BuildSupervision;
use app\base\model\build\BuildSupervisionTem;
use app\base\model\build\BuildSupervisionUser;
use app\base\model\design\DesignPhoto;
use app\base\model\DesignBudgetAccess;
use app\base\model\DesignBudgetListAccess;
use app\base\model\DesignPhase;
use app\base\model\engin\EnginProjectBuildTypeAudit;
use app\base\model\engin\EnginProjectMaterial;
use app\base\model\engin\EnginProjectMaterialAddress;
use app\base\model\engin\EnginProjectMaterialApply;
use app\base\model\engin\EnginProjectMaterialCopy;
use app\base\model\MaterialDataStyle;
use app\base\model\MaterialListEdit;
use app\base\model\PersonnelDepartment;
use app\base\model\PersonnelJobs;
use app\base\model\PersonnelUser;
use app\base\model\Project;
use app\base\model\project\ProjectCollectPricePay;
use app\base\model\ProjectContacts;
use app\base\model\ProjectRelatedPerson;
use app\base\model\DesignBudget;
use app\base\model\ProjectRemindTime;
use app\base\model\ProjectStructure;
use app\base\model\ProjectBuilding;
use app\base\model\ProjectTraceLog;
use app\erp\config\FieldValue;
use app\erp\controller\template_message\SendTemplateMessage;
use think\Db;
use think\Loader;
use think\Session;
use app\erp\config\Config;


class BuildNone extends Auth
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->config_list = Config::$Design;
    }

    public function userJson(){
        $model=new PersonnelUser();
        $department_type=array_search("工程部",FieldValue::getFieldValue("department_type"))?:4;
        $list=$model->getList(["company_id"=>$this->member_info->company_id,'department_type'=>$department_type]);
        return $list;
    }
    /*显示待建项目*/
    public function showBuildProjectList(){
        if ($this->request->isPost()){
            $map=[
                'company_id'=>$this->member_info->company_id,
                'feedback_stage'=>3,
                'engin_status'=>0
            ];
            $list=$this->showEasyUiJsonList("base/Project",false,$map);
            if (!empty($list['rows'])){
                foreach ($list['rows'] as $key=>$value){
                    $obj=Loader::model('base/build/BuildProjectTime')->where(['project_id'=>$value['guid'],'status'=>1])->find();
                    $obj=is_object($obj)? $obj->toArray() : $obj ;
                    if (empty($obj)){
                        $list['rows'][$key]['build_time']="";
                        $list['rows'][$key]['build_days']="";
                        $list['rows'][$key]['build_end_time']="";
                    }else{
                        $list['rows'][$key]['build_time']=date("Y-m-d ",$obj['build_time']);
                        $list['rows'][$key]['build_days']=$obj['build_days'];
                        $list['rows'][$key]['build_end_time']=date("Y-m-d ",$obj['build_time']+$obj['build_days']*60*60*24);
                    }

                }
            }
            return $list;
        }else{
            $arr=[
                'title'=>'待建工程',
                'data_url'=>url('showBuildProjectList'),
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('show_build_project_list');
        }
    }

    /*待建项目列表中的查看项目工程*/
    public function lookBuild($guid=""){
        if (empty($guid)) return self::showReturnCodeWithOutData(1003);
        $numb_model=new BudgetBookNumber();
        if ($this->request->isPost()){
            $list=$this->showEasyUiJsonListNo('base/MaterialDataStyle',false,['company_id'=>$this->member_info->company_id]);
            $model=new DefaultProjectCopy();
            $book_number=$numb_model->where(['project_id'=>$guid,'status'=>1])->value('book_number');
            $price_sum=0;
            $user=Db::table("mk_build_supervision")->where(['project_id'=>$guid,'book_number'=>$book_number,'status'=>1])->value("user_id");
            if(empty($user)){
                $user_name="";
            }else{
                $user_obj=Db::table("mk_personnel_user")->where(["uuid"=>$user])->find();
                $user_name=$user_obj?$user_obj['name'].'('.$user_obj['mobile'].')':"";
            }
            if (!empty($list['rows'])){
                foreach ($list['rows'] as $key=>$value){
                    $project_list=$model->getList(['project_id'=>$guid,'book_number'=>$book_number,'category_id'=>$value['guid'],'pid'=>['<>','0']]);
                    $price_control=0;
                    if (!empty($project_list)){
                        foreach ($project_list as $item){
                            $price_control+=($item['zc_dj']+$item['fc_dj']+$item['rg_dj'])*$item['number'];

                        }
                    }
                    $obj=Loader::model("base/build/BuildProjectCategoryTime")->where(['project_id'=>$guid,'book_number'=>$book_number,'category_id'=>$value['guid'],'status'=>1])->find();
                    $obj=is_object($obj)? $obj->toArray() : $obj ;
                    if (empty($obj)){
                        $list['rows'][$key]['build_time']="";
                        $list['rows'][$key]['build_days']="";
                        $list['rows'][$key]['build_end_time']="";
                        $list['rows'][$key]['build_status']="";
                        $list['rows'][$key]['type']='';
                    }else{
                        $list['rows'][$key]['build_time']=date("Y-m-d ",$obj['build_time']);
                        $list['rows'][$key]['build_days']=$obj['build_days'];
                        $list['rows'][$key]['build_end_time']=date("Y-m-d ",$obj['build_time']+$obj['build_days']*60*60*24);
                        $list['rows'][$key]['type']=$obj['type'];
                        if (time()-($obj['build_time']+$obj['build_days']*60*60*24)>=0){
                            $time=(time()-($obj['build_time']+$obj['build_days']*60*60*24))/(60*60*24);
                            $list['rows'][$key]['build_status']=$time;
                            $list['rows'][$key]['build_status_type']=0;
                        }else{
                            $time=(($obj['build_time']+$obj['build_days']*60*60*24)-time())/(60*60*24);
                            $list['rows'][$key]['build_status']=$time;
                            $list['rows'][$key]['build_status_type']=1;
                        }
                    }
                    $list['rows'][$key]['categories_price']=sprintf("%.2f", $price_control);//显示的时候四舍五入
                    $list['rows'][$key]["sup_name"]=$user_name;
                    $price_sum+=$price_control;
                }
            }
            $list['footer'][]=[
                'categories_name'=>'合计',
                'categories_price'=>sprintf("%.2f", $price_sum)//显示的时候四舍五入
            ];
            return $list;
        }else{
            $arr=[
                'title'=>'项目工程',
                'data_url'=>url('lookBuild',['guid'=>$guid]),
                'pro_id'=>$guid,  //项目id

            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('look_build_project');
        }
    }
    /*待建项目列表中的项目工程的工程明细*/
    public function lookBuildDetailed($pro_id="",$id=""){
        if (empty($pro_id)) return self::showReturnCodeWithOutData(1003);
        if (empty($id)) return self::showReturnCodeWithOutData(1003);
        if ($this->request->isPost()){
            $numb_model=new BudgetBookNumber();
            $model=new DefaultProjectCopy();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $project_list=$model->getList(['project_id'=>$pro_id,'book_number'=>$book_number,'category_id'=>$id,'pid'=>['<>','0']]);
            $num_price=0;
            foreach ($project_list as $value){
                $control_price=0;
                $control_price=$value['zc_dj']+$value['fc_dj']+$value['rg_dj'];
                $value['price_num']=number_format($control_price*$value['number'],2);
                $value['control_price']=$control_price;
                $num_price+=$control_price*$value['number'];
            }
            $project_list[]=[
                'name'=>'合计',
                'price_num'=>$num_price,
            ];
            return $project_list;
        }else{
            $model=new MaterialDataStyle();
            $pro=$model->getInfoByGuId($id);
//            $pro=MaterialDataStyle::quickGet($id);
            $arr=[
                'title'=>'项目工程',
                'data_url'=>url('lookBuildDetailed',['pro_id'=>$pro_id,'id'=>$id]),
                'name'=>$pro['categories_name'],
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('look_build_detailed');
        }
    }
    /*发包打印*/
    public function contractPrint($pro_id=""){
        if (empty($pro_id)) return self::showReturnCodeWithOutData(1003);
        $numb_model=new BudgetBookNumber();
        $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
        if ($this->request->isPost()){
            $data=$this->request->post();
            $model=new BuildContractRint();
            $data['uuid']=$this->uuid;
            $data['project_id']=$pro_id;
            $data['book_number']=$book_number;
            $data['category_id']=implode(',',$data['category_id']);
            if (!isset($data['rate_id'])){
                $data['rate_id']='';
            }else{
                $data['rate_id']=implode(',',$data['rate_id']);
            }
            $data['code']=time().'-'.$book_number;
            $re=$model->saveBuild($data);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="发包预算选择";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $model=new DefaultRateCopy();
            $obj=$model->getList(['project_id'=>$pro_id,'book_number'=>$book_number]);
            $arr=[
                'rate'=>$obj,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('contract_print');
        }
    }
    /*分配监理*/
    public function supervision($pro_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $data['company_id']=$this->member_info->company_id;
            $data['uuid']=$this->uuid;
            $data['project_id']=$pro_id;
            $data['book_number']=$book_number;
            $model=new BuildSupervision();
            $re=$model->saveBuild($data);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="分配监理";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $arr=[
                'url'=>url("showUserJson"),
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('supervision');
        }
    }
    /*整体发包*/
    public function supUser($pro_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $data['company_id']=$this->member_info->company_id;
            $data['uuid']=$this->uuid;
            $data['project_id']=$pro_id;
            $data['book_number']=$book_number;
            $model=new BuildSupervisionTem();
            $re=$model->saveBuildData($data);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="分配发包经理";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $arr=[
                'url'=>url("showUserJson"),
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('supervision');
        }
    }
    /*项目工程的工程施工时间*/
    public function timeBuild($pro_id="",$category_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $validate_time='base/BuildProjectTime.add';
            if ($validate_time!= false) {
                $result = $this->validate($data, $validate_time);
                if (true !== $result) return self::showJsonReturnCodeWithOutData(1003,$result);
            }
            $data['company_id']=$this->member_info->company_id;
            $data['uuid']=$this->uuid;
            $data['project_id']=$pro_id;
            $data['category_id']=$category_id;
            $data['book_number']=$book_number;
            $model=new BuildProjectCategoryTime();
            $re=$model->saveTime($data,$category_id);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="施工时间";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $arr=[
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('time_build');
        }
    }
    /*单项分配发包经理*/
    public function supervisionTem($pro_id="",$category_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $validate_time='base/BuildProjectTime.add';
            if ($validate_time!= false) {
                $result = $this->validate($data, $validate_time);
                if (true !== $result) return self::showJsonReturnCodeWithOutData(1003,$result);
            }
            $data['company_id']=$this->member_info->company_id;
            $data['uuid']=$this->uuid;
            $data['project_id']=$pro_id;
            $data['category_id']=$category_id;
            $data['book_number']=$book_number;
            $model=new BuildSupervisionTem();
            $re=$model->saveBuild($data,$category_id);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="分配单项发包经理";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $arr=[
                'url'=>url("showUserJson"),
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('supervision_tem');
        }
    }
    /*查看工程经理*/
    public function lookBuildUser($pro_id="",$guid=""){
        if(empty($pro_id)) return self::showJsonReturnCode(1003);
        if(empty($guid)) return self::showJsonReturnCode(1003);
        if ($this->request->isPost()){
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $map=[
                'project_id'=>$pro_id,
                'book_number'=>$book_number,
                'category_id'=>$guid,
                'type'=>1,
            ];
            $model=new BuildSupervisionTem();
            $list=$model->getList($map);
            $model_user=new PersonnelUser();
            $model_dep=new PersonnelDepartment();
            $model_jobs=new PersonnelJobs();
            if (!empty($list)){
                foreach ($list as $value){
                    $user=$model_user->getInfoByGuId($value['user_id']);
                    //$user=PersonnelUser::quickGet($value['user_id']);
                    $dep=$model_dep->getInfoByGuId($value['department_id']);
                    //$dep=PersonnelDepartment::quickGet($user['department_id']);
                    $job=$model_jobs->getInfoByGuId($user['jobs_id']);
                    //$job=PersonnelJobs::quickGet($user['jobs_id']);
                    $value['name']=empty($user)?'':$user['name'];
                    $value['jobs_name']=empty($job)?'':$job['jobs_name'];
                    $value['department_name']=empty($dep)?'':$dep['department_name'];
                    $value['mobile']=empty($user)?'':$user['mobile'];
                }
            }
            return $list;
        }else{

            $arr=[
                'url'=>url("lookBuildUser",['pro_id'=>$pro_id,'guid'=>$guid])
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('look_build_user');
        }
    }
    /*删除工程经理*/
    public function delBuildUser(){
        if ($this->request->isPost()){
            $data=$this->request->post();
            $model=new BuildSupervisionTem();
            $re=$model->delBuildUser($data);
            return $re;
        }else{
            return self::showReturnCode(1003);
        }
    }

    /*显示工程部名字*/
    public function showUserJson(){
        if ($this->request->isPost()){
            $department_type=array_search("工程部",FieldValue::getFieldValue("department_type"))?:4;
            $list=$this->showEasyUiJsonList("base/PersonnelUser",false,['company_id'=>$this->member_info->company_id,'department_type'=>$department_type]);
//            $list=$this->showEasyUiJsonList("base/PersonnelUser",false,['company_id'=>$this->member_info->company_id]);
            return $list;
        }else{
            return self::showReturnCode(1003);
        }
    }
    /*预算书查看*/
    public function designBook($guid=""){
        if(empty($guid)) return self::showJsonReturnCode(1003);
        $model=new DefaultProjectCopy();
        $numb_model=new BudgetBookNumber();
        $book_number=$numb_model->where(['project_id'=>$guid,'status'=>1])->value('book_number');
        $data=$model->getDataList($guid,$book_number); //装修信息
        $book=Loader::model("base/budget/DefaultBookCopy")->getBook($guid,$book_number); //公司地址
        $contUser=Loader::model("base/ProjectContacts")->getProjectCont($guid);  //业主的信息
        $pro=Loader::model("base/Project")->getProject($guid); //项目的信息
        if (!empty($pro)){
            if (isset($pro['pro_style'])){
                $fi=new FieldValue();
                $pro['pro_style_name']=$fi->decoration_style[$pro['pro_style']];
            }
        }
        //    $sj_user=Loader::model("base/BudgetDefaultProject")->getUserName($guid);
        $sj_user=Loader::model("base/ProjectRelatedPerson")->getFind(['project_id'=>$guid,'department_type'=>3],'uuid');
        if (empty($sj_user)){
            $user_name='';
        }else{
            $user_name=Loader::model("base/PersonnelUser")->getList(["uuid"=>$sj_user['uuid']],'name,mobile');
        }
        $arr_u=[
            'name'=>empty($user_name) ?"": $user_name[0]['name'] ,
            'tel'=>empty($user_name) ?"":$user_name[0]['mobile'],
        ];
        $field=new FieldValue();
        if (isset($field->decoration_style[$book['budget_style']])){
            $book['budget_style']=$field->decoration_style[$book['budget_style']];
        }
        $assign_data=[
            'book'=>$book,
            'cont'=>$contUser,
            'project'=>$pro,
            'body'=>$data['body'],
            'foot'=>$data['foot'],
            'user'=>$arr_u,
            'book_number'=>$book_number
        ];
        $this->assign($assign_data);
        return $this->fetch('design/book');
    }
    /*发包预算预览*/
    public function contractPrintLook($pro_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if($this->request->isPost()){
            $model=new BuildContractRint();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $arr=$model->returnBuContract($pro_id,$book_number);
            return $arr;
        }else{
            $arr=[
                'contract_url'=>url("contractPrintLook",['pro_id'=>$pro_id]),
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch("contract_print_look");
        }
    }
    /*打印发包预算*/
    public function showContractDesignBook($pro_id=""){
        if (empty($pro_id)) return self::showReturnCodeWithOutData(1003);
        $model=new BuildContractRint();
        $numb_model=new BudgetBookNumber();
        $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
        $data=$model->returnBuContractBook($pro_id,$book_number);
        $book=Loader::model("base/budget/DefaultBookCopy")->getBook($pro_id,$book_number); //公司地址
        $contUser=Loader::model("base/ProjectContacts")->getProjectCont($pro_id);  //业主的信息
        $pro=Loader::model("base/Project")->getProject($pro_id); //项目的信息
        if (!empty($pro)){
            if (isset($pro['pro_style'])){
                $fi=new FieldValue();
                $pro['pro_style_name']=$fi->decoration_style[$pro['pro_style']];
            }
        }
        $sj_user=Loader::model("base/ProjectRelatedPerson")->getFind(['project_id'=>$pro_id,'department_type'=>3],'uuid');
        if (empty($sj_user)){
            $user_name='';
        }else{
            $user_name=Loader::model("base/PersonnelUser")->getList(["uuid"=>$sj_user['uuid']],'name,mobile');
        }
        $arr_u=[
            'name'=>empty($user_name) ?"": $user_name[0]['name'] ,
            'tel'=>empty($user_name) ?"":$user_name[0]['mobile'],
        ];
        $field=new FieldValue();
        if (isset($field->decoration_style[$book['budget_style']])){
            $book['budget_style']=$field->decoration_style[$book['budget_style']];
        }
        $assign_data=[
            'book'=>$book,
            'cont'=>$contUser,
            'project'=>$pro,
            'body'=>$data['rows'],
            'foot'=>$data['footer'],
            'user'=>$arr_u,
            'print_number'=>$data['print_number'],
        ];
        $this->assign($assign_data);
        return $this->fetch('show_contract_design_book');

    }
    /*设置施工总时间*/
    public function constructionTime($project_id=""){
        if (empty($project_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $model=new BuildProjectTime();
            $validate_time='base/BuildProjectTime.add';
            if ($validate_time!= false) {
                $result = $this->validate($data, $validate_time);
                if (true !== $result) return self::showJsonReturnCodeWithOutData(1003,$result);
            }
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$project_id,'status'=>1])->value('book_number');
            $data['company_id']=$this->member_info->company_id;
            $data['uuid']=$this->uuid;
            $data['project_id']=$project_id;
            $data['book_number']=$book_number;
            $data['build_time']=strtotime($data['build_time']);
            $re=$model->saveBuildTime($data);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="设置施工总时间";
                $log["guid"]=$project_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $model=new Project();
            $pro=$model->getInfoByGuId($project_id);
            //$pro=Project::quickGet($project_id);
            $arr=[
                'name'=>$pro['project_name'],
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch("construction_time");
        }
    }
    /*领款百分比设置*/
    public function projectPercentage($pro_id="",$guid=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if (empty($guid)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $validate_time='base/BuildProjectTime.value';
            if ($validate_time!= false) {
                $result = $this->validate($data, $validate_time);
                if (true !== $result) return self::showJsonReturnCodeWithOutData(1003,$result);
            }
            $data['company_id']=$this->member_info->company_id;
            $data['uuid']=$this->uuid;
            $data['project_id']=$pro_id;
            $data['category_id']=$guid;
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $data['book_number']=$book_number;
            $model=new BuildProjectPercentage();
            $re=$model->saveValue($data);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="领款百分比设置";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            self::echoHtml();
            return $this->fetch('project_percentage');
        }
    }
    /*项目阶段领款的金额*/
    public function showProjectPrice($pro_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $model=new BuildProjectPercentage();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $map=[
                'project_id'=>$pro_id,
                'book_number'=>$book_number,
            ];
            $list=$model->getList($map);
            $price=0;
            $sum=0;
            $model=new MaterialDataStyle();
            if (!empty($list)){
                foreach ($list as $value){
                    $category=$model->getInfoByGuId($value['category_id']);
                   // $category=MaterialDataStyle::quickGet($value['category_id']);
                    $sum+=$value['category_price'];
                    $value['category_name']=empty($category)?'': $category['categories_name'];
                    $value['price']=$value['category_price']*$value['value'];
                    $price+=$value['price'];
                    $value['value']=($value['value']*100).'%';
                }
                $list[]=[
                    'category_name'=>'项目完工结算',
                    'price'=>$sum-$price,
                    'value'=>'',
                ];
            }
            return $list;
        }else{
            return self::showReturnCode(1003);
        }
    }

    /*显示我的项目*/
    public function showBuildProjectOfMy(){
        if ($this->request->isPost()){
            $model=new BuildSupervision();
            $list=$model->where(['user_id'=>$this->uuid,'status'=>1])->group('project_id')->select();
            $arr=[];
            $numb_model=new BudgetBookNumber();
            $pro_time=new BuildProjectTime();
            $pro=new Project();
            if (!empty($list)){
                foreach ($list as $value){
                    $book_number=$numb_model->where(['project_id'=>$value['project_id'],'status'=>1])->value('book_number');
                    $project_time=$pro_time->where(['project_id'=>$value['project_id'],'status'=>1,'book_number'=>$book_number])->find();
                    $obj=$pro->getInfoByGuId($value['project_id']);
                    //$obj=Project::quickGet($value['project_id']);
                    $map=[
                        'examine_status'=>0,
                        'project_id'=>$value['project_id'],
                        'status'=>1
                    ];
                    $count=Loader::model('base/engin/EnginProjectCompletionAudit')->where($map)->count();
                    $arr[]=[
                        'guid'=>$value['project_id'],
                        'project_name'=>empty($obj)?"":$obj['project_name'],
                        'project_address'=>empty($obj)?"":$obj['project_address'],
                        'build_time'=>empty($project_time)?'':date("Y-m-d ",$project_time['build_time']),
                        'build_end_time'=>empty($project_time)?'':date("Y-m-d ",$project_time['build_time']+($project_time['build_days']*60*60*24)),
                        'build_days'=>empty($project_time)?'':$project_time['build_days'],
                        'project_completion'=>$count,
                    ];
                }
            }
            $brr=[];
            $brr['rows']=$arr;
            $brr['total']=count($list);
            return $brr;
        }else{
            $arr=[
                'title'=>'我的项目',
                'data_url'=>url("showBuildProjectOfMy"),
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch("show_build_project_my");
        }
    }
    /*我的施工项目的查看工程*/
    public function lookBuildOfMy($guid=""){
        if (empty($guid)) return self::showReturnCode(1003);
        $numb_model=new BudgetBookNumber();
        if ($this->request->isPost()){
            $list=$this->showEasyUiJsonListNo('base/MaterialDataStyle',false,['company_id'=>$this->member_info->company_id]);
            $model=new DefaultProjectCopy();
            $book_number=$numb_model->where(['project_id'=>$guid,'status'=>1])->value('book_number');
            $price_sum=0;
            $arr=[];
            $arr['rows']=[];
            if (!empty($list['rows'])){
                foreach ($list['rows'] as $key=>$value){
                    //查询这个工程类别属不属于
                    $re=Loader::model("base/build/BuildSupervisionTem")->where(['project_id'=>$guid,'book_number'=>$book_number,'category_id'=>$value['guid'],'user_id'=>$this->uuid,'status'=>'1'])->find();
                    if (empty($re)){
//                        unset($list['rows'][$key]);
                        continue;
                    }
                    $project_list=$model->getList(['project_id'=>$guid,'book_number'=>$book_number,'category_id'=>$value['guid'],'pid'=>['<>','0']]);
                    $price_control=0;
                    if (!empty($project_list)){
                        foreach ($project_list as $item){
                            $price_control+=($item['zc_dj']+$item['fc_dj']+$item['rg_dj'])*$item['number'];

                        }
                    }
                    $obj=Loader::model("base/build/BuildProjectCategoryTime")->where(['project_id'=>$guid,'book_number'=>$book_number,'category_id'=>$value['guid'],'status'=>1])->find();
                    $obj=is_object($obj)? $obj->toArray() : $obj ;
                    if (empty($obj)){
                        $list['rows'][$key]['build_time']="";
                        $list['rows'][$key]['build_days']="";
                        $list['rows'][$key]['build_end_time']="";
                        $list['rows'][$key]['type']='';
                        $list['rows'][$key]['build_status']="";
                    }else{
                        $list['rows'][$key]['build_time']=date("Y-m-d ",$obj['build_time']);
                        $list['rows'][$key]['build_days']=$obj['build_days'];
                        $list['rows'][$key]['build_end_time']=date("Y-m-d ",$obj['build_time']+$obj['build_days']*60*60*24);
                        $list['rows'][$key]['type']=$obj['type'];
                        if (time()-($obj['build_time']+$obj['build_days']*60*60*24)>=0){
                            $time=(time()-($obj['build_time']+$obj['build_days']*60*60*24))/(60*60*24);
                            $list['rows'][$key]['build_status']=$time;
                            $list['rows'][$key]['build_status_type']=0;
                        }else{
                            $time=(($obj['build_time']+$obj['build_days']*60*60*24)-time())/(60*60*24);
                            $list['rows'][$key]['build_status']=$time;
                            $list['rows'][$key]['build_status_type']=1;
                        }
                    }
                    $list['rows'][$key]['categories_price']=$price_control;
                    $arr['rows'][]=$value;
                    $price_sum+=$price_control;
                }
            }
            $arr['footer'][]=[
                'categories_name'=>'合计',
                'categories_price'=>$price_sum
            ];
            $arr['total']=$list['total'];
            return $arr;
        }else{

            $arr=[
                'title'=>'项目工程',
                'data_url'=>url('lookBuildOfMy',['guid'=>$guid]),
                'pro_id'=>$guid,  //项目id
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('look_build_project_my');
        }
    }
    /*显示每个工程的领款金额*/
    public function showProjectPriceOfMy($pro_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $model=new BuildProjectPercentage();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $map=[
                'project_id'=>$pro_id,
                'book_number'=>$book_number,
                'status'=>1,
            ];
            $list=$model->getList($map);
            $price=0;
            $sum=0;
            $arr=[];
            $model_type=new MaterialDataStyle();
            if (!empty($list)){
                $num=0;
                foreach ($list as $key=>$value){
                    $re=Loader::model("base/build/BuildSupervisionTem")->where(['project_id'=>$value['project_id'],'book_number'=>$value['book_number'],'category_id'=>$value['category_id'],'user_id'=>$this->uuid,'status'=>1])->find();
                    if (empty($re)){
                        continue;
                    }
                    $category=$model_type->getInfoByGuId($value['category_id']);
                    //$category=MaterialDataStyle::quickGet($value['category_id']);
                    $sum+=$value['category_price'];
                    $value['category_name']=empty($category)?'': $category['categories_name'];
                    $value['price']=$value['category_price']*$value['value'];
                    $price+=$value['price'];
                    $value['value']=($value['value']*100).'%';
                    $app_map=[
                        'project_id'=>$pro_id,
                        'book_number'=>$book_number,
                        'build_id'=>$value['category_id'],
                        'examine_status'=>1,
                        'status'=>1,
                    ];
                    $apply=Loader::model('base/engin/EnginProjectBuildTypeAudit')->where($app_map)->count();
                    $value['apply_status']=$apply;
                    //判断该工程阶段是否已申请领款或是已领取款
                    $get_price=Loader::model('base/project/ProjectCollectPricePay')->where(['old_guid'=>$value['guid'],'status'=>1])->find();
                    $value['get_price']=empty($get_price) ? '-1':$get_price['collect_status'];
                    if ($apply==1){
                        $num++;
                    }
                    $arr[]=$value;
                }
                if(!empty($arr)){
                    $arr[]=[
                        'category_name'=>'项目完工结算',
                        'price'=>$sum-$price,
                        'value'=>'',
                        'apply_status'=>count($arr)==$num?"1":0,
                        'category_id'=>$book_number,
                    ];
                }

            }
            return $arr;
        }else{
            return self::showReturnCode(1003);
        }
    }
    /*分配施工人员*/
    public function supervisionUser($pro_id="",$category_id=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $data['company_id']=$this->member_info->company_id;
            $data['uuid']=$this->uuid;
            $data['project_id']=$pro_id;
            $data['category_id']=$category_id;
            $data['book_number']=$book_number;
            $model=new BuildSupervisionTem();
            $re=$model->saveBuildAdd($data,$category_id);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="分配施工人员";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $arr=[
                'url'=>url("showUserJson"),
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('supervision_user');
        }
    }
    /*查看施工人员*/
    public function lookSupervisionUser($pro_id="",$guid=""){
        if(empty($pro_id)) return self::showJsonReturnCode(1003);
        if(empty($guid)) return self::showJsonReturnCode(1003);
        if ($this->request->isPost()){
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $map=[
                'project_id'=>$pro_id,
                'book_number'=>$book_number,
                'category_id'=>$guid,
                'type'=>2,
            ];
            $model=new BuildSupervisionTem();
            $list=$model->getList($map);
            $model_user=new PersonnelUser();
            $model_dep=new PersonnelDepartment();
            $model_jobs=new PersonnelJobs();
            if (!empty($list)){
                foreach ($list as $value){
                    $user=$model_user->getInfoByGuId($value['user_id']);
                    //$user=PersonnelUser::quickGet($value['user_id']);
                    $dep=$model_dep->getInfoByGuId($value['department_id']);
                    //$dep=PersonnelDepartment::quickGet($user['department_id']);
                    $job=$model_jobs->getInfoByGuId($user['jobs_id']);
                    //$job=PersonnelJobs::quickGet($user['jobs_id']);
                    $value['name']=empty($user)?'':$user['name'];
                    $value['jobs_name']=empty($job)?'':$job['jobs_name'];
                    $value['department_name']=empty($dep)?'':$dep['department_name'];
                    $value['mobile']=empty($user)?'':$user['mobile'];
                }
            }
//            if (!empty($list)){
//                foreach ($list as $value){
//                    $user=PersonnelUser::quickGet($value['user_id']);
//                    $dep=PersonnelDepartment::quickGet($user['department_id']);
//                    $job=PersonnelJobs::quickGet($user['jobs_id']);
//                    $value['name']=empty($user)?'':$user['name'];
//                    $value['jobs_name']=empty($job)?'':$job['jobs_name'];
//                    $value['department_name']=empty($dep)?'':$dep['department_name'];
//                    $value['mobile']=empty($user)?'':$user['mobile'];
//                }
//            }
            $model=new BuildSupervisionTem();
            $obj=$model->where(['project_id'=>$pro_id,'book_number'=>$book_number, 'category_id'=>$guid,'user_id'=>$this->uuid,'status'=>1,'type'=>1])->find();
            if (empty($obj)){
                return [];
            }
            return $list;
        }else{

            $arr=[
                'url'=>url("lookSupervisionUser",['pro_id'=>$pro_id,'guid'=>$guid])
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('look_build_user');
        }

    }
    /*施工图片*/
    public function constructionPhoto($pro_id="",$guid=""){
        if (empty($pro_id)) return self::showReturnCodeWithOutData(1003);
        if (empty($guid)) return self::showReturnCodeWithOutData(1003);
        $numb_model=new BudgetBookNumber();
        $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
        if ($this->request->isPost()){

            $map=[
                'project_id'=>$pro_id,
                'category_id'=>$guid,
                'book_number'=>$book_number,
            ];
            $list=$this->showEasyUiJsonList('base/build/BuildProjectCategoryPhoto',false,$map);
            return $list;
        }else{
            $arr=[
                'url'=>url('constructionPhoto',["pro_id"=>$pro_id,'guid'=>$guid]),
                'guid'=>$guid, //工程类别的id
                'pro_id'=>$pro_id,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('construction_photo');
        }
    }
    /*上传施工图片*/
    public function showAddSchedulePhotoHtml($pro_id="",$guid=""){
        if ($this->request->isPost()){
            if (empty($pro_id)) return self::showReturnCode(1003);
            if (empty($guid)) return self::showReturnCode(1003);
            $data=$this->request->post();
            $model=new BuildProjectCategoryPhoto();
            $numb_model=new BudgetBookNumber();
            $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
            $validate_time='base/ProjectField.addP';
            if ($validate_time!= false) {
                $result = $this->validate($data, $validate_time);
                if (true !== $result) return self::showJsonReturnCodeWithOutData(1003,$result);
            }
            $data['company_id']=$this->member_info->company_id;
            $data['project_id']=$pro_id;
            $data['category_id']=$guid;
            $data['add_uuid']=$this->uuid;
            $data['add_uuid_name']=$this->member_info->name;
            $data['book_number']=$book_number;
            $re=$model->saveBuildPhoto($data);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="上传施工图片";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            self::echoHtml();
            return $this->fetch('engin_project/show_add_build_photo_edit');
        }
    }
    /*删除施工图片*/
    public function delBuildPhoto(){
        if ($this->request->isPost()){
            $data=$this->request->post();
            $model=new BuildProjectCategoryPhoto();
            $re=$model->deletePhoto($data);
            $model_p=new BuildProjectCategoryPhoto();
            if ($re['code']=="1001"){
                if (isset($data["id"])){
                    $pro=$model_p->getInfoByGuId($data['id']);
                    //$pro=BuildProjectCategoryPhoto::quickGet($data['id']);
                }
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="删除施工图片";
                $log["guid"]=empty($pro)?'':$pro['project_id'];
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            return self::showReturnCode(1003);
        }
    }
    /*项目工程阶段的完工申请*/
    public function projectBuildApply($pro_id="",$guid=""){
        if (empty($guid)) return self::showReturnCode(1003);
        $numb_model=new BudgetBookNumber();
        $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
        if ($this->request->isPost()){
            $data=$this->request->post();
            if (empty($data)) return self::showReturnCode(1003);
            $model=new EnginProjectBuildTypeAudit();
            $data['company_id']=$this->member_info->company_id;
            $data['apply_uuid']=$this->uuid;
            $data['apply_name']=$this->member_info->name;
            $data['project_id']=$pro_id;
            $data['book_number']=$book_number;
            $data['category_id']=$guid;
            //判断该工程属不属于他
            $model_name=new BuildSupervisionTem();
            $cate=$model_name->where(['project_id'=>$data['project_id'],'book_number'=>$data['book_number'], 'category_id'=>$guid,'user_id'=>$this->uuid,'status'=>1,'type'=>1])->find();
            if (empty($cate)){
                return self::showReturnCode(1003,[],'数据变动，请刷新数据');
            }
            $re=$model->addBuildCategoryAudit($data,$guid);
            if ($re['code']=="1001"){
                $title="项目阶段完工申请";
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]=$title;
                $log["guid"]=$guid;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
                //项目阶段完工通知验收
                SendTemplateMessage::sendTemplateMessage('projectStageCheck');
            }
            return $re;
        }else{
            $arr=[

            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('engin_project/build_cont_apply');
        }
    }
    /*工程阶段完工验收*/
    public function auditBuildApply($guid=""){
        if (empty($guid)) return self::showReturnCode(1003);
        if ($this->request->isPost()){
            $data=$this->request->post();
            $model=new EnginProjectBuildTypeAudit();
            $data['examine_uuid']=$this->uuid;
            $data['examine_name']=$this->member_info->name;
            $re=$model->auditBuildCategoryApply($data,$guid);
            $model_p=new EnginProjectBuildTypeAudit();
            if ($re['code']=="1001"){
                $obj=$model_p->getInfoByGuId($guid);
                //$obj=EnginProjectBuildTypeAudit::quickGet($guid);
                $title=$data['examine_status']=="1"?"项目阶段完工验收通过":"项目阶段完工验收不通过";
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]=$title;
                $log["guid"]=$obj['project_id'];
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return  $re;
        }else{
            return self::showReturnCode(1003);
        }
    }
    /*领款申请*/
    public function projectPriceApply($pro_id="",$guid=""){
        if (empty($pro_id)) return self::showReturnCode(1003);
        if (empty($guid)) return self::showReturnCode(1003);
        $numb_model=new BudgetBookNumber();
        $book_number=$numb_model->where(['project_id'=>$pro_id,'status'=>1])->value('book_number');
        if ($this->request->isPost()){
            $data=$this->request->post();
            $validate_time='base/ProjectCollectPricePay.add';
            if ($validate_time!= false) {
                $result = $this->validate($data, $validate_time);
                if (true !== $result) return self::showJsonReturnCodeWithOutData(1003,$result);
            }
            $data['collect_uuid']=$this->uuid;
            $data['collect_uuid_name']=$this->member_info->name;
            $data['company_id']=$this->member_info->company_id;
            $data['project_id']=$pro_id;
            $data['book_number']=$book_number;
            $model=new ProjectCollectPricePay();
            $re=$model->addPaymentProPrice($data,$guid);
            if ($re['code']=="1001"){
                $model_log=new ProjectTraceLog();
                $log=[];
                $log["log_content"]="项目阶段的领款申请";
                $log["guid"]=$pro_id;
                $log["uuid"]=$this->uuid;
                $log["jobs_id"]=$this->member_info->jobs_id;
                $log["department_id"]=$this->member_info->department_id;
                $model_log->addProjectLog($log);
            }
            return $re;
        }else{
            $model=new Project();
            $project=$model->getInfoByGuId($pro_id);
            //$project=Project::quickGet($pro_id);
            if ($guid==$book_number){  //说明是最后结清款
                $map=[
                    'project_id'=>$pro_id,
                    'status'=>1,
                    'cetegory_uuid'=>$this->uuid,
                ];
                $list=Loader::model("base/build/BuildProjectPercentage")->where($map)->select();
                $price=0;
                if (!empty($list)){
                    foreach ($list as $value){
                        $price+=$value['category_price']*(1-$value['value']);
                    }
                }
            }else{
                $map=[
                    'project_id'=>$pro_id,
                    'category_id'=>$guid,
                    'status'=>1,
                    'book_number'=>$book_number,
                ];
                $value=Loader::model("base/build/BuildProjectPercentage")->where($map)->find();
                $price=empty($value)? '0':$value['category_price']*$value['value'];
            }

            $arr=[
                'number'=>$book_number,
                'name'=>empty($project)?"":$project['project_name'],
                'check'=>'',
                'value'=>$price,
            ];
            $this->assign($arr);
            self::echoHtml();
            return $this->fetch('add_payment_pro');
        }
    }
    /*显示付款详细*/
    public function showPayDetailed($guid=""){
        if (empty($guid)) return self::showReturnCodeWithOutData(1003);
        $model=new ProjectCollectPricePay();
        $obj=$model->getInfoByGuId($guid);
        $project_name=Loader::model("base/Project")->where(['guid'=>$obj['project_id']])->value('project_name');
        if (empty($obj['payment_id'])){
            $payment='';
        }else{
            $payment=Loader::model('base/finance/PaymentStyle')->where(['guid'=>$obj['payment_id']])->value('name');
        }
        $assign_data= [
            'name'=>$project_name,
            'obj'=>$obj,
            'ex'=>$obj['collect_status']=="1"?'已收款':'未收款',
            'examine'=>$obj['examine_status']=="1"?'审核通过':'未审核或审核不通过',
            'invoice'=>$obj['invoice_value']==0?'无发票':'开发票',
            'payment'=>$payment
        ];
        $this->assign($assign_data);
        self::echoHtml();
        return $this->fetch('project_collection/show_detailed');
    }


    //项目变更()
    public function changeProject($pro_id=""){
        if (empty($pro_id)) return self::showJsonReturnCode(1003);
        if ($this->request->isPost()){

        }else{

        }
    }


}