<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/23
 * Time: 13:02
 */

namespace app\erp\controller;

use app\base\controller\Upload;
use app\base\model\Base;
use app\base\model\budget\BudgetBookNumber;
use app\base\model\budget\DefaultProjectCopy;
use app\base\model\budget\DefaultRateCopy;
use app\base\model\build\BuildContractRint;
use app\base\model\build\BuildProjectPercentage;
use app\base\model\build\BuildProjectTime;
use app\base\model\build\BuildSupervisionTem;
use app\base\model\finance\Bank;
use app\base\model\finance\BankTransactionRecord;
use app\base\model\finance\CollectPlan;
use app\base\model\finance\CollectPlanAccess;
use app\base\model\finance\CollectStyle;
use app\base\model\finance\PaymentStyle;
use app\base\model\MaterialDataStyle;
use app\base\model\PersonnelDepartment;
use app\base\model\PersonnelJobs;
use app\base\model\PersonnelUser;
use app\base\model\Project;
use app\base\model\project\ProjectCollectPhoto;
use app\base\model\project\ProjectCollectPlan;
use app\base\model\project\ProjectCollectPrice;
use app\base\model\project\ProjectContract;
use app\base\model\project\ProjectField;
use app\base\model\project\ProjectPhoto;
use app\base\model\ProjectContacts;
use app\base\model\ProjectRemindTime;
use app\base\model\ProjectStructure;
use app\base\model\ProjectBuilding;
use app\base\model\ProjectTraceLog;
use app\erp\config\FieldValue;
use mikkle\tp_wechat\support\Db;
use think\Loader;
use think\Session;
use app\erp\config\Config;


class FinanceProjectPrice extends Auth
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->config_list = Config::$project;
    }
    /*显示已签合同项目*/
    public function showProjectList(){
        if ($this->request->isPost()){
            $page=$this->request->param("page")?$this->request->param("page"):'1';
            $rows=$this->request->param("rows")?$this->request->param("rows"):"20";
            $project_name=$this->request->param('project_name')?$this->request->param('project_name'):"";
            $number=$this->request->param('book_number')?$this->request->param('book_number'):"";
            $model=new ProjectContract();
            $list=$model->showProjectList($rows,$page,$project_name,$number);
            return $list;
        }else{
            config(['default_ajax_return' => 'html',]);
            $assign_data= [
                'title' => '已签合同项目表',
                'dialog_url' => '',
                'data_url' => url('showProjectList'),
            ];
            $this->assign($assign_data);
            return $this->fetch('show_contract_project_list');
        }
    }
   /* 查看已签合同项目的收支明细*/
    public function lookProjectMore($guid=""){
        if(empty($guid)){
            return self::showJsonReturnCode(1003);
        }
        $model=new ProjectContract();
        $obj=$model->getInfoByGuId($guid);
        $add_list=Db::table("mk_project_collect_price")
            ->field(['collect_type_name','sum(collect_price)'=>'price'])
            ->where(['status'=>1,
                'project_id'=>$obj["project_id"],
                'collect_status'=>1,
                'book_number'=>$obj["book_number"]
                ]
            )
            ->group("collect_type")
            ->select();
        $pay_list=Db::table("mk_project_collect_price_pay")
            ->field(['collect_type_name','sum(collect_price)'=>'price'])
            ->where(['status'=>1,
                    'project_id'=>$obj["project_id"],
                    'collect_status'=>1,
                    'book_number'=>$obj["book_number"]
                ]
            )
            ->group("collect_type")
            ->select();
        if (!empty($obj)){
            $loss=$obj["price"]-$obj["pay_price"];
        }
        $arr=[
            'title'=>'项目信息',
            'obj'=>$obj,
            'add_url'=>url("showPriceInfo",["project_id"=>$obj["project_id"]]),
            'pay_url'=>url("showPriceInfoPay",["project_id"=>$obj["project_id"]]),
            'add'=>$add_list,
            'pay'=>$pay_list,
            "loss"=>$loss>0?"盈利：".$loss:"亏损：".$loss,
        ];
        $this->assign($arr);
        return $this->fetch('look_project_more');
    }
    /*	显示具体的收入明细*/
    public function showPriceInfo($project_id=""){
        if(empty($project_id)){
            return self::showJsonReturnCode(1003);
        }
        if ($this->request->isPost()){
            $list=$this->showEasyUiJsonList("base/finance/BankTransactionRecord",false,["project_id"=>$project_id,'finance_mode'=>1]);
            return $list;
        }else{
            return self::showJsonReturnCode(1003);

        }
    }
    /*显示具体的支出明细*/
    public function showPriceInfoPay($project_id=""){
        if(empty($project_id)){
            return self::showJsonReturnCode(1003);
        }
        if ($this->request->isPost()){
            $list=$this->showEasyUiJsonList("base/finance/BankTransactionRecord",false,["project_id"=>$project_id,'finance_mode'=>2]);
            return $list;
        }else{
            return self::showJsonReturnCode(1003);

        }
    }
}