<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/23
 * Time: 13:02
 */

namespace app\erp\controller;

use app\base\controller\Upload;
use app\base\model\Base;
use app\base\model\budget\BudgetBookNumber;
use app\base\model\budget\DefaultProjectCopy;
use app\base\model\budget\DefaultRateCopy;
use app\base\model\build\BuildContractRint;
use app\base\model\build\BuildProjectPercentage;
use app\base\model\build\BuildProjectTime;
use app\base\model\build\BuildSupervisionTem;
use app\base\model\finance\Bank;
use app\base\model\finance\BankTransactionRecord;
use app\base\model\finance\CollectPlan;
use app\base\model\finance\CollectPlanAccess;
use app\base\model\finance\CollectStyle;
use app\base\model\finance\PaymentStyle;
use app\base\model\MaterialDataStyle;
use app\base\model\PersonnelCompany;
use app\base\model\PersonnelDepartment;
use app\base\model\PersonnelJobs;
use app\base\model\PersonnelUser;
use app\base\model\Project;
use app\base\model\project\ProjectCollectPhoto;
use app\base\model\project\ProjectCollectPlan;
use app\base\model\project\ProjectCollectPrice;
use app\base\model\project\ProjectContract;
use app\base\model\project\ProjectField;
use app\base\model\project\ProjectPhoto;
use app\base\model\finance\RevokeMoney;
use app\base\model\ProjectContacts;
use app\base\model\ProjectRemindTime;
use app\base\model\ProjectStructure;
use app\base\model\ProjectBuilding;
use app\base\model\ProjectTraceLog;
use app\erp\config\FieldValue;
use app\erp\controller\template_message\SendTemplateMessage;
use think\Loader;
use think\Session;
use app\erp\config\Config;


class FinanceRevoke extends Auth
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->config_list = Config::$project;
    }
    /*已收款的撤销申请*/
    public function revokeMoney($guid=""){
        if(empty($guid)){
            return self::showJsonReturnCode(1003);
        }
        if ($this->request->isPost()){
            $data=$this->request->post();
            $validate_name='base/ApplyModel.apply_track';
            $result = $this->validate($data, $validate_name);
            if (true !== $result) return ['code' => '1003', 'msg' => $result,];
            $data['uuid']=$this->member_info->uuid;
            $data['company_id']=$this->member_info->company_id;
            $data["collect_id"]=$guid;
            $model=new RevokeMoney();
            $re=$model->saveApplyData($data);
            if ($re['code']=="1001") {
                $log_model = new ProjectTraceLog();
                $collect_model=new ProjectCollectPrice();
                $obj=$collect_model->getInfoByGuId($guid);
                $log = [];
                $log["log_content"] = "已收款撤销申请,原因是".$data["apply_desc"];
                $log["guid"] = empty($obj)?"":$obj["project_id"];
                $log["uuid"] = $this->member_info->uuid;
                $log["jobs_id"] = $this->member_info->jobs_id;
                $log["department_id"] = $this->member_info->department_id;
                $log_model->addProjectLog($log);
                SendTemplateMessage::sendTemplateMessage('revokeCheck');
            }
            return $re;
        }else{
            self::echoHtml();
            return $this->fetch('apply_model/track_log');
        }
    }
    /*已收款撤销审核列表*/
    public function showRevokeList(){
        if ($this->request->isPost()){
            $list=$this->showEasyUiJsonList("base/finance/revokeMoney",false,["examine_status"=>0,'company_id'=>$this->member_info->company_id]);
            return $list;
        }else{
            $arr=[
                'title'=>"撤销申请列表",
                'data_url'=>url("showRevokeList"),
                'edit_url'=>url("editApply"),
            ];
            $this->assign($arr);
            return $this->fetch("show_revoke_list");
        }
    }
    /*已收款撤销审核权限*/
    public function editApply($guid=""){
        if(empty($guid)){
            return self::showJsonReturnCode(1003);
        }
        if ($this->request->isPost()){
            $data=$this->request->post();
            $model=new RevokeMoney();
            $data["examine_uuid"]=$this->uuid;
            $data["examine_name"]=$this->member_info->name;
            $re=$model->editApply($data,$guid);
            if ($re['code']=="1001") {
                $log_model = new ProjectTraceLog();
                $collect_model=new ProjectCollectPrice();
                $obj=$collect_model->getInfoByGuId($guid);
                $log = [];
                if ($data['examine_status']=="1"){
                    $title="已收款撤销审核通过";
                }else if($data['examine_status']=="-1"){
                    $title="已收款撤销审核不通过";
                }else{
                    $title="已收款撤销审核";
                }
                $log["log_content"] = $title;
                $log["guid"] = empty($obj)?"":$obj["project_id"];
                $log["uuid"] = $this->member_info->uuid;
                $log["jobs_id"] = $this->member_info->jobs_id;
                $log["department_id"] = $this->member_info->department_id;
                $log_model->addProjectLog($log);
            }
            return $re;
        }else{
            self::echoHtml();
            return $this->fetch('apply_model/track_log_edit');
        }
    }
    /*查看撤销的款项明细*/
    public function showMoreInfo($guid=""){
        if (empty($guid)) return self::showJsonReturnCode(1003);
        $model=new ProjectCollectPrice();
        $obj=$model->getInfoByGuId($guid);

        $obj=$model->getTime($obj,'collect_date',false);
        $project_name=Loader::model("base/Project")->where(['guid'=>$obj['project_id']])->value('project_name');
        if (empty($obj['payment_id'])){
            $payment='';
        }else{
            $payment=Loader::model('base/finance/PaymentStyle')->where(['guid'=>$obj['payment_id']])->value('name');
        }
        $com_model=new PersonnelCompany();
        $company=$com_model->getInfoByGuId($this->member_info->company_id);
        $assign_data= [
            'name'=>$project_name,
            'obj'=>$obj,
            'company'=>$company?$company["company_name"]:'',
            'ex'=>$obj['collect_status']=="1"?'已收款':'未收款',
            'examine'=>$obj['examine_status']=="1"?'审核通过':'未审核或审核不通过',
            'invoice'=>$obj['invoice_value']==0?'无发票':'开发票',
            'payment'=>$payment
        ];
        $this->assign($assign_data);
        self::echoHtml();
        return $this->fetch('show_detailed');
    }
}