<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/23
 * Time: 13:02
 * 资金汇总
 */

namespace app\erp\controller;

use app\base\controller\Upload;
use app\base\model\Base;
use app\base\model\budget\BudgetBookNumber;
use app\base\model\budget\DefaultProjectCopy;
use app\base\model\budget\DefaultRateCopy;
use app\base\model\build\BuildContractRint;
use app\base\model\build\BuildProjectPercentage;
use app\base\model\build\BuildProjectTime;
use app\base\model\build\BuildSupervisionTem;
use app\base\model\finance\Bank;
use app\base\model\finance\BankTransactionRecord;
use app\base\model\finance\CollectPlan;
use app\base\model\finance\CollectPlanAccess;
use app\base\model\finance\CollectStyle;
use app\base\model\finance\PaymentStyle;
use app\base\model\MaterialDataStyle;
use app\base\model\PersonnelCompany;
use app\base\model\PersonnelDepartment;
use app\base\model\PersonnelJobs;
use app\base\model\PersonnelUser;
use app\base\model\Project;
use app\base\model\project\ProjectCollectPhoto;
use app\base\model\project\ProjectCollectPlan;
use app\base\model\project\ProjectCollectPrice;
use app\base\model\project\ProjectContract;
use app\base\model\project\ProjectField;
use app\base\model\project\ProjectPhoto;
use app\base\model\finance\RevokeMoney;
use app\base\model\ProjectContacts;
use app\base\model\ProjectRemindTime;
use app\base\model\ProjectStructure;
use app\base\model\ProjectBuilding;
use app\base\model\ProjectTraceLog;
use app\erp\config\FieldValue;
use app\erp\controller\template_message\SendTemplateMessage;
use mikkle\tp_wechat\support\Db;
use think\Loader;
use think\Session;
use app\erp\config\Config;


class FundsSum extends Auth
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->config_list = Config::$project;
    }
    /*资金汇总列表*/
    public function showFundsList(){
        if($this->request->isPost()){
            $list=Db::view("mk_finance_bank a","name,uuid_name,guid,balance_price")
                ->view("mk_finance_bank_transaction_record b",["sum(income_price)"=>"profit_price","sum(expenditure_price)"=>"loss_price"],"a.guid=b.bank_id")
                ->where("a.company_id",$this->member_info->company_id)
                ->where('a.status','1')
                ->group("b.bank_id")
                ->select();
            $arr=[];
            $arr["rows"]=$list;
            $profit=0;
            $loss=0;
            $sum=0;
            if (!empty($list)){
                foreach ($list as $value){
                    $loss+=$value["loss_price"];
                    $profit+=$value["profit_price"];
                    $sum+=$value["balance_price"];
                }
            }
            $arr["footer"][]=[
                'name'=>"合计",
                'profit_price'=>$profit,
                'loss_price'=>$loss,
                'balance_price'=>$sum,
            ];
            $arr["total"]=count($list);
           return $arr;
        }else{
            $arr=[
                'title'=>'资金汇总表',
                'data_url'=>url("showFundsList"),
            ];
            $this->assign($arr);
            return $this->fetch("show_funds_list");
        }
    }












}