<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/23
 * Time: 13:02
 * 主材商城
 */

namespace app\erp\controller;

use app\base\model\Base;
use app\base\model\Material;
use app\base\model\MaterialCategory;
use app\base\model\MaterialDataStyle;
use app\base\model\MaterialTemplateBudgetAccess;
use app\base\model\PersonnelDepartment;
use app\base\model\PersonnelUser;
use app\base\model\ProjectContacts;
use app\base\model\ProjectRelatedPerson;
use app\base\model\ProjectRemindTime;
use app\base\model\ProjectStructure;
use app\base\model\ProjectBuilding;
use app\base\model\ProjectTraceLog;
use app\erp\config\FieldValue;
use phpDocumentor\Reflection\Types\Object_;
use think\Loader;
use think\Session;
use app\erp\config\Config;


class MaterialMarket extends Auth
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->config_list = Config::$Material;
    }
    /*主材商城数据*/
    public function showMarketData(){
        if ($this->request->isPost()){
            $map=[
                'company_id'=>$this->member_info->company_id,
                'show_mark'=>1,
                'type'=>1
            ];
            $field="material_name,material_photo,category_id,update_time,material_desc";
            $list=$this->showEasyUiJsonList("base/Material",false,$map,false,[],false,$field);
            $type=new MaterialCategory();
            if (!empty($list['rows'])){
                foreach ($list['rows'] as $key=>$value){
                    $type=$type->getInfoByGuId($value['category_id']);
                    $list['rows'][$key]['category_id']=empty($type)?'材料':$type['category_name'];
                }
            }
            return $list;
        }else{
            return self::showJsonReturnCode(1003);
        }
    }
    public function showType(){

    }
    public function showMarketDataCopy(){
        if ($this->request->isPost()){
            $data=$this->request->post();
            $model=new Material();
            $map=[
                'company_id'=>$this->member_info->company_id,
                'show_mark'=>1,
                'type'=>1
            ];
            $field="material_name,material_photo,category_id,update_time,material_desc";
            $list=$model->showMaterialList($data,$map,$field);
            $type=new MaterialCategory();
            if (!empty($list['rows'])){
                foreach ($list['rows'] as $key=>$value){
                    $type=$type->getInfoByGuId($value['category_id']);
                    $list['rows'][$key]['category_id']=empty($type)?'材料':$type['category_name'];
                }
            }
            return $list;
        }else{
            return self::showJsonReturnCode(1003);
        }
    }

}